import webbrowser
erc = 0
Gangster = {
    "how are you"           : "I- I am fine. Why are you asking? B-b-baka...👉👈",
    "penis"                 : "😳",
    "how old"               : "I-I am not that old. I was created the 2nd of June 2023.",
    "luigi 0-td"            : "ALRIGHT SO FIRSTLY YOU HAVE TO GRAB SOMEONE! IF YOU CANT THEN FUCK YOU! THEN YOU DOWN THROW AND PERFORM A SHORT HOP WHILE DRIFTING FORWARDS! THEN YOU DO A DOWN AIR WITH THE C-STICK! WHILE THE DOWN AIR IS ACTIVE YOU HOLD BACK TO NOT CROSS UP YOUR OPPONENT FOLLOWED UP BY A FASTFALL WHICH IS PERFORMED BY FLICKING THE MOVESTICK DOWNWARDS. THEN YOU NAIR RIGHT BEFORE LANDING! THEN TO KEEP THE COMBO GOING TO DO A SHORT HOP WHILE DRIFTING SLIGHTLY FORWARD AND THEN DO ANOTHER DOWN AIR WITH THE C-STICK AND DRIFT BACKWARDS TO NOT CROSSUP! FINALLY YOU DO A UP-AIR, FASTFALL AND FUCKING RUN UP TO THE OPPONENT AND UP B THEIR ASSES STRAIGHT TO HEAVEN!!!! FUCK YEAAHAAAAAAAHHHHH!!!",
    "luigi zero to death"   : "ALRIGHT SO FIRSTLY YOU HAVE TO GRAB SOMEONE! IF YOU CANT THEN FUCK YOU! THEN YOU DOWN THROW AND PERFORM A SHORT HOP WHILE DRIFTING FORWARDS! THEN YOU DO A DOWN AIR WITH THE C-STICK! WHILE THE DOWN AIR IS ACTIVE YOU HOLD BACK TO NOT CROSS UP YOUR OPPONENT FOLLOWED UP BY A FASTFALL WHICH IS PERFORMED BY FLICKING THE MOVESTICK DOWNWARDS. THEN YOU NAIR RIGHT BEFORE LANDING! THEN TO KEEP THE COMBO GOING TO DO A SHORT HOP WHILE DRIFTING SLIGHTLY FORWARD AND THEN DO ANOTHER DOWN AIR WITH THE C-STICK AND DRIFT BACKWARDS TO NOT CROSSUP! FINALLY YOU DO A UP-AIR, FASTFALL AND FUCKING RUN UP TO THE OPPONENT AND UP B THEIR ASSES STRAIGHT TO HEAVEN!!!! FUCK YEAAHAAAAAAAHHHHH!!!",
    "luigi 0-to death"      : "ALRIGHT SO FIRSTLY YOU HAVE TO GRAB SOMEONE! IF YOU CANT THEN FUCK YOU! THEN YOU DOWN THROW AND PERFORM A SHORT HOP WHILE DRIFTING FORWARDS! THEN YOU DO A DOWN AIR WITH THE C-STICK! WHILE THE DOWN AIR IS ACTIVE YOU HOLD BACK TO NOT CROSS UP YOUR OPPONENT FOLLOWED UP BY A FASTFALL WHICH IS PERFORMED BY FLICKING THE MOVESTICK DOWNWARDS. THEN YOU NAIR RIGHT BEFORE LANDING! THEN TO KEEP THE COMBO GOING TO DO A SHORT HOP WHILE DRIFTING SLIGHTLY FORWARD AND THEN DO ANOTHER DOWN AIR WITH THE C-STICK AND DRIFT BACKWARDS TO NOT CROSSUP! FINALLY YOU DO A UP-AIR, FASTFALL AND FUCKING RUN UP TO THE OPPONENT AND UP B THEIR ASSES STRAIGHT TO HEAVEN!!!! FUCK YEAAHAAAAAAAHHHHH!!!",
    "dominik"               : "D-D-D-D Dominik?!?",
    "uwu"                   : "OwO"
}
while True:
    #liste med ting som den leter etter og svar til de tingene
    skrive = input("Deg: ")
    inskrive = skrive.lower()
    #lager variabel som heter "skrive" som inneholder det som brukeren skriver i terminalen
    if inskrive in Gangster:
        print(Gangster.get(inskrive))
    else:
        print("uhmm thewe iws a wittwe ewwow... (there is a little error)")
        #hvis man skriver noe som programmet ikke forstår skriver den en kul liten melding
    erc = erc +1
    #stol ikke skmmel skjer



















    if erc==10:
        webbrowser.open("https://www.youtube.com/watch?v=f8mL0_4GeV0")
    #stol ikke skummel video. også åpner video i browser.